fixed errors in all files
added tabs to lines and found and fixed errors in files. also renamed bashbd.sh to bashbd as indicated in the Learnign the Bash Shell book.

diff --git a/bashdb b/bashdb
--- a/bashdb
+++ b/bashdb
@@ -3,16 +3,21 @@
 # and then executes the new script.
 echo 'bash Debugger version 1.0'
 _dbname=${0##*/}
+
 if (( $# < 1 )) ; then
-echo "$_dbname: Usage: $_dbname filename" >&2
-exit 1
+    echo "$_dbname: Usage: $_dbname filename" >&2
+    exit 1
 fi
+
 _guineapig=$1
+
 if [ ! -r $1 ]; then
-echo "$_dbname: Cannot read file '$_guineapig'." >&2
-exit 1
+    echo "$_dbname: Cannot read file '$_guineapig'." >&2
+    exit 1
 fi
+
 shift
+
 _tmpdir=/tmp
 _libdir=.
 _debugfile=$_tmpdir/bashdb.$$ # temporary file for script being debugged
